### ISSUE TITLE
Error !!

### ISSUE THREAD

**Issue by danzee1** [n0kovo/DomainDouche#2] opened 2022-12-04 14:11 UTC
Showing this error while running the command:

"UNRECOGNIZED REPLY! TRY WITH FRESH COOKIE."

Tried it multiple times with new cookies but still same response...

**Comment by n0kovo** [comment] 2022-12-04 20:05
Are you using both the cookies and the user-agent from the same browser/session?

**Comment by danzee1** [comment] 2022-12-05 05:04
Yes... using same browser's user agent & cookies ,, i carefully read the instructions.

**Comment by n0kovo** [comment] 2022-12-05 18:01
I am not able to reproduce. What does your final command look like?

**Comment by n0kovo** [comment] 2022-12-09 22:24
Closing due to lack of communication

**Closed as completed by n0kovo** 2022-12-09 22:24 UTC
